define(["jquery", "console"], function($, console) {
	console.log("MULTILANGUAGE INIT");

	//  data-lang="ko"
	//  data-lang="en"
	//  data-lang="ja"
	$.lang = {};
	$.langPlaceholder = {};

	$.lang.ko = {
		0: '&nbsp;&nbsp;&nbsp;실행중…',	// loading.html

		1: '새로운 모듈이 연결되었습니다.',	// main.html
		2: '모터 123',

		3: '열기',	// menubox.html
		4: '새로만들기',
		5: '저장',
		6: '다른 이름으로 저장',
		7: '시작하는 법',
		8: '업데이트 확인',
		9: '질문하기',

		10: '시작하는 법',	// modal.html
		11: '새로 만들기',
		12: 'Noneㅎㅎㅎㅎㅎ',
		13: 'Noneㅎㅎㅎㅎㅎ',
		14: 'Noneㅎㅎㅎㅎㅎ',
		15: '열기',
		16: 'Settingㅎㅎㅎㅎㅎ',
		17: 'Resetㅎㅎㅎㅎㅎ',
		18: '시작하는법',
		19: '뒤로가기',
		20: 'Your browser does not support the video tag.ㅎㅎㅎㅎㅎ',
		21: '새로만들기',
		// 22: '',
		23: '사용할 모듈을 선택해 주세요.',
		24: 'Bluetoothㅎㅎㅎㅎㅎ',
		25: '만들기',
		26: 'A project with this name already exists. Please change the project nameㅎㅎㅎㅎㅎ.',
		27: '열기',
		// 28: '',
		29: '열기',
		30: '업로드',
		31: '코딩한 내용으로 펌웨어 업데이트를 진행합니다.',
		32: '기존에 모듈을 동작시키던 펌웨어가 삭제됩니다. 계속 진행하시겠습니까?<p> *주의:삭제된 펌웨어는 복구할 수 없습니다.</p>',
		// 33: '',
		34: '펌웨어 업로드 실패',
		35: '펌웨어 업로드 성공',
		36: '세부내용보기',
		37: '다시는 이 메시지를 보지 않습니다.',
		38: '펌웨어 업로드가 진행중입니다.',
		39: '펌웨어 업로드 중에는 모듈 연결을 임의로 끊지 마십시오. 모듈에게 치명적인 손상을 가할 수 있습니다.',
		40: '세부내용숨기기',
		41: '닫기',
		42: 'Module Settingㅎㅎㅎㅎㅎ',
		43: 'Propertyㅎㅎㅎㅎㅎ',
		44: 'Monitoringㅎㅎㅎㅎㅎ',
		45: 'Nameㅎㅎㅎㅎㅎ',
		46: 'IDㅎㅎㅎㅎㅎ',
		// 47: '',
		// 48: '',
		// 49: '',
		// 50: '',
		// 51: '',
		// 52: '',
		53: '<span>An error occurred. Please see the event log belowㅎㅎㅎㅎㅎ.</span>',
		54: '<span>The software update is completeㅎㅎㅎㅎㅎ.</span>',
		55: 'Networkㅎㅎㅎㅎㅎ',
		56: '<span>Memoryㅎㅎㅎㅎㅎ<br>/Flash</span>',
		57: 'Networkㅎㅎㅎㅎㅎ',
		58: 'Statusㅎㅎㅎㅎㅎ',
		59: 'Systemㅎㅎㅎㅎㅎ',
		60: 'Open Projectㅎㅎㅎㅎㅎ',
		// 61: '',
		62: 'Save change to the project "Untitled" before opening the new project?<br>By clicking "Do not save" will open the new project without saving changesㅎㅎㅎㅎㅎ.',
		63: 'Do you want to close this project and go back to the main page? Your project progress is automatically savedㅎㅎㅎㅎㅎ.',
		64: 'Saveㅎㅎㅎㅎㅎ',
		65: 'Don\'t Saveㅎㅎㅎㅎㅎ',
		// 66: '',
		// 67: '',
		68: 'Save Projectㅎㅎㅎㅎㅎ',
		69: 'Saveㅎㅎㅎㅎㅎ',
		70: 'previewㅎㅎㅎㅎㅎ',
		71: 'Check Updateㅎㅎㅎㅎㅎ',
		72: 'Software version checkingㅎㅎㅎㅎㅎ..',
		73: '<b>The software version is the most recent version availableㅎㅎㅎㅎㅎ.</b>',
		74: 'Current versionㅎㅎㅎㅎㅎ',
		75: 'Latest versionㅎㅎㅎㅎㅎ',
		76: 'Last Updateㅎㅎㅎㅎㅎ',
		77: 'Module detectㅎㅎㅎㅎㅎ',
		78: '<span>Type of new module detected already exists.<br> Do you want to apply information in existed module to the new module detectedㅎㅎㅎㅎㅎ?</span>',
		// 79: '',
		// 80: '',
		81: 'Settingㅎㅎㅎㅎㅎ',
		82: 'Errorㅎㅎㅎㅎㅎ',
		83: 'Exitㅎㅎㅎㅎㅎ',
		84: '모듈을 처음 받아 본 상태로 초기화 합니다',
		85: '모듈을 처음 받아 본 상태로 초기화 합니다.',
		86: '모듈을 처음 받아 본 상태로 초기화를 진행하면, 모듈을 동작시키던 펌웨어가 삭제됩니다. 계속 진행하시겠습니까?',
		87: 'Update firmware of current project. Existing firmware will be deleted. Do you want to update?<p> * Caution : You cannot restore deleted firmwareㅎㅎㅎㅎㅎ.</p>',
		88: 'Select the language you want the MODI Studio to useㅎㅎㅎㅎㅎ.',
		89: 'Network Module Settingㅎㅎㅎㅎㅎ',
		90: 'Wifiㅎㅎㅎㅎㅎ',
		91: 'WiFi hotspot modeㅎㅎㅎㅎㅎ',
		92: 'The Network module operates as a router functionㅎㅎㅎㅎㅎ.',
		93: 'WiFi auto connect moduleㅎㅎㅎㅎㅎ',
		94: 'The Network module automatically connects to specified router.ㅎㅎㅎㅎㅎ',
		95: 'Bluetoothㅎㅎㅎㅎㅎ',
		96: '취소',
		97: '확인',

		98: 'Module boxㅎㅎㅎㅎㅎ',	// modulebox.html
		99: '모듈',
		100: '그룹모듈',
		101: 'Module setㅎㅎㅎㅎㅎ',
		102: '<b>변수모듈</b>',
		103: '<b>INPUT모듈(가상)</b>',
		104: '<b>OUTPUT모듈(가상)</b>',
		105: '<b>SETUP모듈(가상)</b>',
		106: '<b>그룹모듈</b>',
		// 107: '',
		// 108: '',
		// 109: '',
		// 110: '',
		// 111: '',
		// 112: '',
		// 113: '',
		// 114: '',
		// 115: '',
		// 116: '',
		// 117: '',
		// 118: '',
		// 119: '',
		120: 'Otherㅎㅎㅎㅎㅎ',
		121: 'Segwayㅎㅎㅎㅎㅎ',
		122: 'Bipadㅎㅎㅎㅎㅎ',

		123: 'Timeㅎㅎㅎ',	// monitoring.html
		124: 'Module Monitoringㅎㅎㅎㅎㅎ',
		125: 'switch axis scaleㅎㅎㅎㅎㅎ',
		126: '닫기',
		127: '그래프',
		128: '표',
		129: 'Exportㅎㅎㅎ',

		130: 'Module Settingㅎㅎㅎ',	// rename.html
		131: '닫기',

		132: 'Battery Average :&nbsp;ㅎㅎㅎ',		// title.html
		133: '업로드',
		134: '모듈동작정지',
		135: '그래픽언어',	
		136: '컴퓨터언어',
		137: '모듈초기화',
		138: '모듈동작확인',
		139: '커뮤니티',

		140: 'Drag and drop a block hereㅎㅎㅎㅎㅎ',	// action.js

		141: 'Please enter function on the blank above manually or choose from lists on left columnㅎㅎㅎㅎㅎ',	// editor.js
		142: 'minㅎㅎㅎㅎㅎ',
		143: 'maxㅎㅎㅎㅎㅎ',
		144: 'timesㅎㅎㅎㅎㅎ',
		145: 'msㅎㅎㅎㅎㅎ',
		// 146: '',
		// 147: '',
		148: '확인',
		// 149: '',
		// 150: '',
		// 151: '',

		152: '비교할 값이 같을때로 조건을 설정할 수 있습니다.',		//guiblock.js
		153: '다음에 입력할 값 보다 크거나 같을때로 조건을 설정할 수 있습니다.',
		154: '다음에 입력할 값 보다 작거나 같을때로 조건을 설정할 수 있습니다.',
		155: '비교할 값이 같지 않을 때로 조건을 설정할 수 있습니다.',
		156: '다음에 입력할 값 보다 클때로 조건을 설정할 수 있습니다.',
		157: '다음에 입력할 값 보다 작을때로 조건을 설정할 수 있습니다.',
		158: '',
		159: '버튼 모듈이 클릭 된 순간을 조건으로 설정할 수 있습니다.',
		160: '버튼 모듈이 더블클릭 된 순간을 조건으로 설정할 수 있습니다.',
		161: '버튼 모듈의 눌림 상태값에 따른 조건을 설정할 수 있습니다.',
		162: '버튼이 눌릴 때 마다 값이 100 <-> 0 으로 전환됩니다. 눌릴 때 마다 변화하는 값에 따른 조건을 설정할 수 있습니다.',
		163: '마이크 모듈에서 측정되는 소음의 양에 따른 조건을 설정할 수 있습니다.',
		164: '마이크 모듈에서 측정되는 소리의 주파수에 따른 조건을 설정할 수 있습니다.',
		165: '다이얼 모듈의 회전한 각도 값에 따른 조건을 설정할 수 있습니다.',
		166: '적외선 모듈의 근접한 정도에 따른 조건을 설정할 수 있습니다.',
		167: '환경모듈에서 측정되는 온도 값으로 조건을 설정할 수 있습니다.',
		168: '환경모듈에서 측정되는 습도 값으로 조건을 설정할 수 있습니다.',	
		169: '환경모듈에서 측정되는 밝기 값으로 조건을 설정할 수 있습니다.',
		170: '환경모듈에서 측정되는 빨간색 조명값으로 조건을 설정할 수 있습니다.',
		171: '환경모듈에서 측정되는 초록색 조명값으로 조건을 설정할 수 있습니다.',
		172: '환경모듈에서 측정되는 파란색 조명값으로 조건을 설정할 수 있습니다.',
		173: '자이로 모듈에서 X축을 바탕으로 회전된 각도값에 따른 조건을 설정할 수 있습니다.',
		174: '자이로 모듈에서 Y축을 바탕으로 회전한 각도값에 따른 조건을 설정할 수 있습니다.',
		175: '자이로 모듈에서 Z축을 바탕으로 회전한 각도값에 따른 조건을 설정할 수 있습니다.',
		176: '자이로 모듈에서 X축을 바탕으로 이동하였을때 측정된 가속도 값에 따른 조건을 설정할 수 있습니다.',
		177: '자이로 모듈에서 Y축을 바탕으로 이동하였을때 측정된 가속도 값에 따른 조건을 설정할 수 있습니다.',
		178: '자이로 모듈에서 Z축을 바탕으로 이동하였을때 측정된 가속도 값에 따른 조건을 설정할 수 있습니다.',
		179: '자이로 모듈에서 X축을 바탕으로 회전하는 속도값에 따른 조건을 설정할 수 있습니다.',
		180: '자이로 모듈에서 Y축을 바탕으로 회전하는 속도값에 따른 조건을 설정할 수 있습니다.',
		181: '자이로 모듈에서 Z축을 바탕으로 회전하는 속도값에 따른 조건을 설정할 수 있습니다.',
		182: '자이로 모듈이 흔들리는 정도에 따른 조건을 설정할 수 있습니다.',
		183: '초음파 모듈로 측정되는 거리 값에 따른 조건을 설정할 수 있습니다.',
		// 184: '',
		185: '기본적으로 설정된 색상(파랑, 초록, 빨강 또는 흰색)으로 LED의 색을 표현할 수 있습니다.',
		186: 'Use \'Custom Color\' to use various color and brightnessㅎㅎㅎㅎㅎ',
		187: '색상 맵에서 원하는 색상을 선택할 수 있습니다. 선택된 색상으로 LED의 색을 표현할 수 있습니다.',
		188: 'LED module emits color by combining three colorㅎㅎㅎㅎㅎ',
		189: '모터의 축이 입력한 각도의 위치로 이동합니다.',
		190: 'Motor shaft turns as much as the angle enteredㅎㅎㅎㅎㅎ',
		191: '모터의 축이 입력한 속도로 계속 회전합니다.',
		192: 'Enter negative value will turn in reverse directionㅎㅎㅎㅎㅎ',
		193: '모터의 축이 입력한 힘을 유지하며 계속 회전합니다.',
		194: 'Torque means motor\'s powerㅎㅎㅎㅎㅎ',
		195: '스피커 모듈에서 선택된 피아노 음으로 소리를 출력합니다.',
		196: 'Speaker module makes sound by selected pitchㅎㅎㅎㅎㅎ',
		197: '스피커 모듈에서 입력된 주파수에 해당하는 음을 출력합니다.',
		198: 'Frequency means Speaker module\'s pitchㅎㅎㅎㅎㅎ',
		199: '디스플레이 모듈에 그림을 그릴 수 있습니다.',
		200: 'Try drawing your favorite pictureㅎㅎㅎㅎㅎ',
		201: '디스플레이 모듈에 텍스트를 입력할 수 있습니다.',
		202: 'You can also show function valuesㅎㅎㅎㅎㅎ',
		203: 'Please enter function on the blank above manually or choose from lists on left columnㅎㅎㅎㅎㅎ',
		204: 'Choose a color.ㅎㅎㅎㅎㅎ',
		205: 'Redㅎㅎㅎㅎㅎ',
		206: 'Greenㅎㅎㅎㅎㅎ',
		207: 'Blueㅎㅎㅎㅎㅎ',
		208: 'Whiteㅎㅎㅎㅎㅎ',
		209: 'Offㅎㅎㅎㅎㅎ',
		210: 'Select the blank above and enter angleㅎㅎㅎㅎㅎ',
		211: 'Select the blank above and enter speedㅎㅎㅎㅎㅎ',
		212: 'Select the blank above and enter torqueㅎㅎㅎㅎㅎ',
		213: 'Enter a frequency of Speaker module on the blank aboveㅎㅎㅎㅎㅎ',
		214: 'Enter text into the field above to be shown on the displayㅎㅎㅎㅎㅎ',
		215: 'Red line is a character that cannot be displayedㅎㅎㅎㅎㅎ',
		216: '',
		217: '',
		218: '',
		219: '',
		220: '',
		221: '',
		222: '',
		223: '',
		224: '',
		225: 'Percentage in unit(%RH) - 0 ~ 100%RHㅎㅎㅎㅎㅎ',
		226: 'Percentage in unit(°) - 0 ~ 270°ㅎㅎㅎㅎ',
		227: 'Percentage in unit(cm) - 0 ~ 500cmㅎㅎㅎㅎㅎ',
		228: 'Percentage in unit(cm) - 0 ~ 50cmㅎㅎㅎㅎㅎ',
		229: 'Percentage in unit(%) - 0 ~ 100%ㅎㅎㅎㅎㅎ',
		230: 'Percentage in unit(lux) 0 ~ 4000luxㅎㅎㅎㅎㅎ',
		231: 'Percentage in unit(°) - -90 ~ 90°ㅎㅎㅎㅎㅎ',
		232: 'Percentage in unit(m/s) - -19.6 ~ 19.6m/sㅎㅎㅎㅎㅎ',
		233: 'Percentage in unit(Hz) 50 ~ 400Hzㄱㄱㄱㄱㄱ',
		234: 'Percentage in unit(℃) - -40 ~ 100℃ㅎㅎㅎㅎㅎ',
		235: '',
		236: '버튼 모듈의 측정값으로 조건을 만들 수 있습니다.',
		237: '마이크 모듈의 측정값으로 조건을 만들 수 있습니다.',
		238: '다이얼 모듈의 측정값으로 조건을 만들 수 있습니다.',
		239: '적외선 모듈의 측정값으로 조건을 만들 수 있습니다.',
		240: '환경 모듈의 측정값으로 조건을 만들 수 있습니다.',
		241: '자이로 모듈의 측정값으로 조건을 만들 수 있습니다.',
		242: '초음파 모듈의 측정값으로 조건을 만들 수 있습니다.',
		243: 'Set a condition by using Motor moduleㅎㅎㅎㅎㅎ',
		244: 'Set a condition by using Led moduleㅎㅎㅎㅎㅎ',
		245: 'Set a condition by using Display moduleㅎㅎㅎㅎㅎ',
		246: 'Set a condition by using Speaker moduleㅎㅎㅎㅎㅎ',
		247: '생성한 숫자값에 맞춰서 조건을 설정할 수 있습니다.',
		248: '네트워크 모듈에서 수신되는 데이터 값을 사용하여 조건을 만들 수 있습니다.',
		249: '무작위로 변화하는 숫자값에 맞춰서 조건을 설정할 수 있습니다.',
		250: 'Please enter function on the blank above manually or choose from lists on left columnㅎㅎㅎㅎㅎ',
		251: '네트워크 모듈에서 수신되는 데이터 값을 사용하여 조건을 만들 수 있습니다.',
		252: '네트워크 모듈과 블루투스로 연결된 MODI App에서 사용하는 UI에 따른 조건을 만들 수 있습니다.',
		// 253: '',
		// 254: '',
		// 255: '',
		// 256: '',
		// 257: '',

		// 258: '',	// mapmodule.js
		// 259: '',
		// 260: '',
		// 261: '',		//  data-langNum="140"
		// 262: '',
		263: '디스플레이 모듈에 그림을 그리거나 글자를 적을 수 있습니다. 왼쪽에서 사용할 기능을 선택해 주세요.',
		264: '스피커 모듈에서 피아노 건반을 선택하거나 소리의 주파수를 입력하여 지정한 음을 낼 수 있습니다. 왼쪽에서 소리를 낼 기능을 선택해주세요.',
		265: 'LED에 선택된 색상으로 빛을 낼 수 있습니다. 왼쪽에서 빛을 낼 기능을 선택해 주세요.',
		266: '모터가 지정한 각도로 회전하거나, 입력된 속도, 힘으로 계속 회전시킬 수 있습니다. 왼쪽에서 모터를 회전시킬 기능을 선택해 주세요.',
		267: 'WHILE블록은 조건을 설정하는 블록입니다. 첫번째 빈칸을 클릭하여 조건을 만들어 봅시다.',
		268: 'IF블록은 조건을 설정하는 블록입니다. 첫번째 빈칸을 클릭하여 조건을 만들어 봅시다.',
		269: 'randomrandomrandomrandomrandomrandomㅎㅎㅎㅎㅎ',
		270: 'numbernumbernumbernumbernumbernumbeㅎㅎㅎㅎㅎ'
		


	};



	//  data-langNum="0"
	// 추후 title.js의 gui/cui부분 hover, click 시 글자 바뀌는 부분도 해야 함.
	$.lang.en = {
		0: '&nbsp;&nbsp;&nbsp;Loading...',	// loading.html

		1: 'New Module detected!',	// main.html
		2: 'Motor 123',

		3: 'Open',	// menubox.html
		4: 'New',
		5: 'Save',
		6: 'Save As',
		7: 'Tutorial',
		8: 'Update Check',
		9: 'Q&A',

		10: 'Getting Started',	// modal.html
		11: 'New Project',
		12: 'None',
		13: 'None',
		14: 'None',
		15: 'Open As',
		16: 'Setting',
		17: 'Reset',
		18: 'Getting Started',
		19: 'Go Back',
		20: 'Your browser does not support the video tag.',
		21: 'New project',
		// 22: '',
		23: 'Choose MODI set and enter a name for the project.',
		24: 'Bluetooth',
		25: 'Create',
		26: 'A project with this name already exists. Please change the project name.',
		27: 'Open Project',
		// 28: '',
		29: 'Open',
		30: 'Upload',
		31: 'Update firmware of current project.',
		32: 'Existing firmware will be deleted. Do you want to update?<p data-langNum="32"> * Caution : You cannot restore deleted firmware.</p>',
		// 33: '',
		34: 'Update failed',
		35: 'Update success',
		36: 'Show details',
		37: 'Always allow. Do not show this message again.',
		38: 'Update in progress..',
		39: 'DO NOT disconnect module while firmware update is in progress, damage may occur.',
		40: 'Hide details',
		41: 'Close',
		42: 'Module Setting',
		43: 'Property',
		44: 'Monitoring',
		45: 'Name',
		46: 'ID',
		// 47: '',
		// 48: '',
		// 49: '',
		// 50: '',
		// 51: '',
		// 52: '',
		53: '<span>An error occurred. Please see the event log below.</span>',
		54: '<span>The software update is complete.</span>',
		55: 'Network',
		56: '<span>Memory<br>/Flash</span>',
		57: 'Network',
		58: 'Status',
		59: 'System',
		60: 'Open Project',
		// 61: '',
		62: 'Save change to the project "Untitled" before opening the new project?<br>By clicking "Do not save" will open the new project without saving changes.',
		63: 'Do you want to close this project and go back to the main page? Your project progress is automatically saved.',
		64: 'Save',
		65: 'Don\'t Save',
		// 66: '',
		// 67: '',
		68: 'Save Project',
		69: 'Save',
		70: 'preview',
		71: 'Check Update',
		72: 'Software version checking..',
		73: '<b>The software version is the most recent version available.</b>',
		74: 'Current version',
		75: 'Latest version',
		76: 'Last Update',
		77: 'Module detect',
		78: '<span>Type of new module detected already exists.<br> Do you want to apply information in existed module to the new module detected?</span>',
		// 79: '',
		// 80: '',
		81: 'Setting',
		82: 'Error',
		83: 'Exit',
		84: 'Restore default settings',
		85: 'Restore default settings.',
		86: 'Restoring default settings will remove all module settings that you have configured. <br>Do you want to restore all settings to default?',
		87: 'Update firmware of current project. Existing firmware will be deleted. Do you want to update?<p> * Caution : You cannot restore deleted firmware.</p>',
		88: 'Select the language you want the MODI Studio to use.',
		89: 'Network Module Setting',
		90: 'Wifi',
		91: 'WiFi hotspot mode',
		92: 'The Network module operates as a router function.',
		93: 'WiFi auto connect module',
		94: 'The Network module automatically connects to specified router.',
		95: 'Bluetooth',
		96: 'Cancel',
		97: 'OK',

		98: 'Module box',	// modulebox.html
		99: 'Module',
		100: 'Downloaded',
		101: 'Module set',
		102: '<b>Variable Module</b>',
		103: '<b>Input Module</b>',
		104: '<b>Output Module</b>',
		105: '<b>Setup Module</b>',
		106: '<b>Downloaded</b>',
		// 107: '',
		// 108: '',
		// 109: '',
		// 110: '',
		// 111: '',
		// 112: '',
		// 113: '',
		// 114: '',
		// 115: '',
		// 116: '',
		// 117: '',
		// 118: '',
		// 119: '',
		120: 'Other',
		121: 'Segway',
		122: 'Bipad',

		123: 'Time',	// monitoring.html
		124: 'Module Monitoring',
		125: 'switch axis scale',
		126: 'Close',
		127: 'Graph',
		128: 'Table',
		129: 'Export',

		130: 'Module Setting',	// rename.html
		131: 'Close',

		132: 'Battery Average :&nbsp;',		// title.html
		133: 'Upload',
		134: 'Pause',
		135: 'CUI',	
		136: 'GUI',
		137: 'Reset',
		138: 'Play',
		139: 'Community',

		140: 'Drag and drop a block here',	// action.js

		141: 'Please enter function on the blank above manually or choose from lists on left column',	// editor.js
		142: 'min',
		143: 'max',
		144: 'times',
		145: 'ms',
		// 146: '',
		// 147: '',
		148: 'OK',
		// 149: '',
		// 150: '',
		// 151: '',

		152: '',		//guiblock.js
		153: '',
		154: '',
		155: '',
		156: '',
		157: '',
		158: '',
		159: 'Set a condition by clicking Button module',
		160: 'Set a condition double clicking Button module',
		161: 'Set a condition by pressing Button module',
		162: 'Set a condition by toggling Button module',
		163: 'Set a condition by decibel Microphone module measures',
		164: 'Set a condition by frequency Microphone module measures',
		165: 'Set a condition by turning Dial module',
		166: 'Set a condition by proximity Infrared module measures',
		167: 'Set a condition by temperature Environment module measures',
		168: 'Set a condition by humidity Environment module measures',	
		169: 'Set a condition by illuminance Environment module measures',
		170: 'Set a condition by red color illuminance Environment module measures',
		171: 'Set a condition by green color illuminance Environment module measures',
		172: 'Set a condition by blue color illuminance Environment module measures',
		173: 'Set a condition by change of X-axis of Gyroscope module',
		174: 'Set a condition by change of Y-axis of Gyroscope module',
		175: 'Set a condition by change of Z-axis of Gyroscope module',
		176: 'Set a condition by change of X-axis acceleration of Gyroscope module',
		177: 'Set a condition by change of Y-axis acceleration of Gyroscope module',
		178: 'Set a condition by change of Z-axis acceleration of Gyroscope module',
		179: 'Set a condition by change of X-axis of Gyroscope module',
		180: 'Set a condition by change of Y-axis of Gyroscope module',
		181: 'Set a condition by change of Z-axis of Gyroscope module',
		182: 'Set a condition by change of vibration of Gyroscope module.',
		183: 'Set a condition by distance Ultrasonic module measures',
		// 184: '',
		185: 'Select a color from left column. LED module emit selected color(Red, Green, Blue, White) light',
		186: 'Use \'Custom Color\' to use various color and brightness',
		187: 'Choose a color on the color picker below. LED module emit the customized color light',
		188: 'LED module emits color by combining three color',
		189: 'Enter an angle of Motor module on the blank above. Motor shaft turns as much as the angle entered',
		190: 'Motor shaft turns as much as the angle entered',
		191: 'Enter a speed of motor module on the blank above. Motor shaft turns as much as the speed entered',
		192: 'Enter negative value will turn in reverse direction',
		193: 'Enter a torque of motor module on the blank above. Motor shaft turns as much as the torque entered',
		194: 'Torque means motor\'s power',
		195: 'Select a syllable from piano below. Speaker module makes the selected syllable sound',
		196: 'Speaker module makes sound by selected pitch',
		197: 'Adjust frecuency and volume of speaker module',
		198: 'Frequency means Speaker module\'s pitch',
		199: 'Draw a picture to be shown on the Display module',
		200: 'Try drawing your favorite picture',
		201: 'Enter text to be shown on the Display',
		202: 'You can also show function values',
		203: 'Please enter function on the blank above manually or choose from lists on left column',
		204: 'Choose a color.',
		205: 'Red',
		206: 'Green',
		207: 'Blue',
		208: 'White',
		209: 'Off',
		210: 'Select the blank above and enter angle',
		211: 'Select the blank above and enter speed',
		212: 'Select the blank above and enter torque',
		213: 'Enter a frequency of Speaker module on the blank above',
		214: 'Enter text into the field above to be shown on the display',
		215: 'Red line is a character that cannot be displayed',
		216: '',
		217: '',
		218: '',
		219: '',
		220: '',
		221: '',
		222: '',
		223: '',
		224: '',
		225: 'Percentage in unit(%RH) - 0 ~ 100%RH',
		226: 'Percentage in unit(°) - 0 ~ 270°',
		227: 'Percentage in unit(cm) - 0 ~ 500cm',
		228: 'Percentage in unit(cm) - 0 ~ 50cm',
		229: 'Percentage in unit(%) - 0 ~ 100%',
		230: 'Percentage in unit(lux) 0 ~ 4000lux',
		231: 'Percentage in unit(°) - -90 ~ 90°',
		232: 'Percentage in unit(m/s) - -19.6 ~ 19.6m/s',
		233: 'Percentage in unit(Hz) 50 ~ 400Hz',
		234: 'Percentage in unit(℃) - -40 ~ 100℃',
		235: '',
		236: 'Set a condition by using Button module',
		237: 'Set a condition by using Mic module',
		238: 'Set a condition by using Dial module',
		239: 'Set a condition by using Infrared',
		240: 'Set a condition by using Environment module',
		241: 'Set a condition by using Gyroscope module',
		242: 'Set a condition by using Ultrasonic module',
		243: 'Set a condition by using Motor module',
		244: 'Set a condition by using Led module',
		245: 'Set a condition by using Display module',
		246: 'Set a condition by using Speaker module',
		247: '',		// 한글이 있는 애
		248: 'Set a condition by using Network module',
		249: '',		// 한글이 있는 애
		250: 'Please enter function on the blank above manually or choose from lists on left column',
		251: '',		// 한글이 있는 애
		252: '',		// 한글이 있는 애
		// 253: '',
		// 254: '',
		// 255: '',
		// 256: '',
		// 257: '',

		// 258: '',	// mapmodule.js
		// 259: '',
		// 260: '',
		// 261: '',		//  data-langNum="140"
		// 262: '',
		263: 'Please enter function on the blank above manually or choose from lists on left column',
		264: 'Please enter function on the blank above manually or choose from lists on left column',
		265: 'Please enter function on the blank above manually or choose from lists on left column',
		266: 'Please enter function on the blank above manually or choose from lists on left column',
		267: 'Please enter function on the blank above manually or choose from lists on left column',
		268: 'Please enter function on the blank above manually or choose from lists on left column',
		269: 'randomrandomrandomrandomrandomrandom',
		270: 'numbernumbernumbernumbernumbernumber'
		

		// 271: '',	// modal.js
		// 272: '',
		// 273: '',
		// 274: '',		//  data-langNum="140"
		// 275: '',
		// 276: '',
		// 277: '',
		// 278: '',
		// 279: '',
		// 280: '',
		// 281: '',
		// 282: '',
		// 283: '',
		// 284: '',
		// 285: '',
		// 286: '',
		// 287: '',
		// 288: '',
		// 289: '',		//  data-langNum="140"
		// 290: '',
		// 291: '',
		// 292: '',
		// 293: '',
		// 294: '',
		// 295: '',
		// 296: '',
		// 297: '',
		// 298: '',
		// 299: '',
		// 300: '',
		// 301: '',
		// 302: '',
		// 303: '',
		// 304: '',		//  data-langNum="140"
		// 305: '',
		// 306: '',
		// 307: '',
		// 308: '',
		// 309: '',
		// 310: '',
		// 311: '',
		// 312: '',
		// 313: '',
		// 314: '',
		// 315: '',
		// 316: '',
		// 317: '',
		// 318: '',
		// 319: '',
		// 320: '',
		// 321: '',
		// 322: '',
		// 323: '',
		// 324: '',
		// 325: '',
		// 326: '',
		// 327: '',		//  data-langNum="140"
		// 328: '',
		// 329: '',
		// 330: '',
		// 331: '',
		// 332: '',
		// 333: '',
		// 334: '',
		// 335: '',
		// 336: '',
		// 337: '',
		// 338: '',
		// 339: '',
		// 340: '',
		// 341: '',
		// 342: '',
		// 343: '',
		// 344: '',
		// 345: '',
		// 346: '',
		// 347: '',
		// 348: '',
		// 349: '',
		// 350: '',
		// 351: '',		//  data-langNum="140"
		// 352: '',
		// 353: '',
		// 354: '',
		// 355: '',
		// 356: ''
		

	};



	$.langPlaceholder.ko = {
		0: '프로젝트 이름을 입력해 주세요.',
		1: '프로젝트 이름',
		2: '',
		3: '',	
		4: '검색',
		5: '비밀번호',
		6: '',
		7: ''
	};

	$.langPlaceholder.en = {
		0: 'Enter project name', 		//modal.html
		1: 'Project Name',
		2: 'Name',
		3: 'PIN code',	
		4: 'Search',			//modulebox.html
		5: 'Password',			//modal.js
		6: '',
		7: ''
	};


	function setLanguage(currentLanguage) {
		console.log("setLanguage", arguments);

		$("[data-langNum]").each(function() {
			$(this).html($.lang[currentLanguage][$(this).data("langnum")]); 
		});	

		$("[data-langPlaceholder]").each(function() {
			$(this).attr("placeholder", $.langPlaceholder[currentLanguage][$(this).data("langplaceholder")]);
		});


		if(currentLanguage == "en") {
			$(".menubox > .projectBox").css({"width": "100px"});
		} else if(currentLanguage == "ko") {
			$(".menubox > .projectBox").css({"width": "130px"});
		}
	}  		


	$(document).ready(function() {
	});

	return {
		setLanguage: setLanguage
	};
});


